// One-line catalog of every level: docs/GAME-LIST.md (year, title, id).
// Usage: npm run list. Regenerate after pool changes.
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ROOT = process.cwd()
const rows = []

const tsv = await readFile(path.join(ROOT, 'src', 'data', 'games.tsv'), 'utf8')
for (const line of tsv.split('\n').slice(1)) {
  if (!line.trim()) continue
  const c = line.split('\t')
  rows.push({ id: c[0], title: c[1], year: Number(c[2]), src: 'hand' })
}
for (const f of ['games.auto.ts', 'games.custom.ts']) {
  const raw = await readFile(path.join(ROOT, 'src', 'data', f), 'utf8').catch(() => '')
  // commented-out examples (custom.ts) must not parse as entries
  const t = raw.split('\n').filter((l) => !l.trimStart().startsWith('//')).join('\n')
  for (const m of t.matchAll(/\{[^{}]*\}/g)) {
    const b = m[0]
    if (b.trimStart().startsWith('//')) continue
    const id = b.match(/id:\s*'([^']+)'/)?.[1] ?? b.match(/"id"\s*:\s*"([^"]+)"/)?.[1]
    const title = b.match(/title:\s*'([^']+)'/)?.[1] ?? b.match(/"title"\s*:\s*"([^"]+)"/)?.[1]
    const year = Number(b.match(/year:\s*(\d+)/)?.[1] ?? b.match(/"year"\s*:\s*(\d+)/)?.[1])
    if (id && title && year) rows.push({ id, title, year, src: f === 'games.auto.ts' ? 'auto' : 'custom' })
  }
}
rows.sort((a, b) => a.year - b.year || a.title.localeCompare(b.title))
const hand = rows.filter((r) => r.src === 'hand').length
const auto = rows.filter((r) => r.src === 'auto').length
const custom = rows.filter((r) => r.src === 'custom').length
const out = [
  `# Guess the Game — title list (${rows.length} levels: ${hand} hand + ${auto} auto + ${custom} custom)`,
  '',
  '_Generated by `npm run list` — do not edit._',
  '',
  ...rows.map((r) => `- ${r.year} — **${r.title}** (\`${r.id}\`)`),
  '',
]
await writeFile(path.join(ROOT, 'docs', 'GAME-LIST.md'), out.join('\n'))
console.log(`wrote docs/GAME-LIST.md (${rows.length} titles)`)
